### PR TITLE
[FEATURE] Make Trade UI same as on RT (RT-3436)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Make the Trade-Advanced UI the same as on Ripple Trade

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before
rt-3436-before

**Comment by darkdarkdragon** [comment]
after
rt-3436-after1

**Comment by darkdarkdragon** [comment]
after 2
rt-3436-after2

**Comment by vhpoet** [comment]
LGTM

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
