### PR TITLE
[TASK] Bare bones cold wallet page (DC-25)

### PR DESCRIPTION
**Pull request by MatthewPhinney**

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
@vhpoet let me know how this looks.  It has most of the functionality requested, but zero styling.

**Comment by annatonger** [comment]
@MatthewPhinney  can you include a screenshot please?

**Comment by MatthewPhinney** [comment]
screen shot 2015-09-15 at 3 56 19 pm

Like I said, no styling.  At this point, I'm more concerned about the information presented.  If it's sufficient, we can add style later.

**Comment by annatonger** [comment]
I don't get what this page is for @vhpoet

**Comment by vhpoet** [comment]
Let's wait for Dave's comments.

**Comment by dncohen** [comment]
The purpose of this page is to show a user of the offline client all the data they will need.  So this is shown on an online machine, the user can manually copy details like sequence number and fee to the offline machine.

Some thoughts (thinking out loud, open to alternatives)...

Show the ripple address along with the account information.
Nice to have: brief description of the last transaction, i.e. "Transaction #522 issued 1,000 USD to r1234... on Sept 10, 2015"

Move the network fee to a network section.  That section would ideally show an incrementing ledger sequence and current time.

I'm a big fan of human readable explanations, as shown in the warnings.  Would be great to have the same along with the account settings.  Is that what "best practices" links to?

I believe we will get away from "trust lines", so text may need to change for that, but that is another topic.

Thanks!

**Comment by MatthewPhinney** [comment]
I've made note of Dave's comments and included them in DC-97, which is a task for moving this functionality to the login screen.  Can we merge this PR?  I will then work the remainder of this task under DC-97.

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
