### PR TITLE
[TASK] Add/Edit trustlines offline (DC-34)

### PR DESCRIPTION
**Pull request by MatthewPhinney**

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
@vhpoet I pushed a new commit.  If it looks good, I'll rebase.

**Comment by vhpoet** [comment]
@MatthewPhinney it's good for now. @mrajvanshy is gonna implement a global sequence number thing, which will overwrite some of this stuff.

**Comment by MatthewPhinney** [comment]
@vhpoet I squashed the commits.

**Comment by vhpoet** [comment]
LGTM

**Pull request merged**
