### PR TITLE
[FIX] use latest node-webkit (RT-3418)

### PR DESCRIPTION
**Pull request by darkdarkdragon**

### CODE REVIEW

**Comment by yongsoo** [comment]
@darkdarkdragon Did you build this, and test functionality for all tabs / settings for both funded and unfunded wallets?

**Comment by darkdarkdragon** [comment]
@yongsoo I've built this. On windows I've tested all functionality and almost all settings. Found problem - if you delete one server from settings, when client do not load anymore.
On Ubuntu x32 and x64 tested only Send tab
On Mac not tested

**Comment by darkdarkdragon** [comment]
And this all was on funded wallet

**Comment by yongsoo** [comment]
Can you test fully? Test all the flows on unfunded wallet too make sure it looks good. Thanks @darkdarkdragon !

**Comment by darkdarkdragon** [comment]
@yongsoo ok, I just fix other tasks first, and then will test all at once

**Comment by yongsoo** [comment]
Sure that sounds good @darkdarkdragon thank you!

**Comment by darkdarkdragon** [comment]
@yongsoo I've commited all my other fixes into this one brunch so I can test them all at once.
On windows I've tested all the tabs - on funded and on unfunded accounts.
I've not run this on Mac

**Comment by darkdarkdragon** [comment]
after
rt-3418-after01

rt-3418-after02

**Comment by darkdarkdragon** [comment]
checked on MacOS - works well

**Pull request closed without merging**
