### PR TITLE
[FEATURE] Edit DefaultRipple flag (RT-3401)

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Add ability to Enable/Disable DefaultRipple flag

### CODE REVIEW

**Comment by darkdarkdragon** [comment]
before

rt-3401-before

**Comment by darkdarkdragon** [comment]
after
rt-3401-after1

**Comment by darkdarkdragon** [comment]
after
rt-3401-after2

**Comment by yongsoo** [comment]
LGTM

**Pull request merged**
