### PR TITLE
[TASK] Add txn info to submit page (DC-77)

### PR DESCRIPTION
**Pull request by MatthewPhinney**

### CODE REVIEW

**Comment by MatthewPhinney** [comment]
screen shot 2015-11-09 at 10 31 38 am

**Comment by MatthewPhinney** [comment]
What do you think of this UI?

**Comment by mrajvanshy** [comment]
Do we still want to have the file name of the transaction on this view as well?

**Comment by MatthewPhinney** [comment]
screen shot 2015-11-09 at 11 30 55 am

**Comment by MatthewPhinney** [comment]
Added filename; removed box around result message text; fixed row padding.

**Comment by mrajvanshy** [comment]
LGTM

**Pull request merged**
